agents:
  queue: kubernetes
steps:
  - label: "🐍 Run Python Tests"
    plugins:
      - docker#v5.12.0:
          image: "python:3.12"
          mount-buildkite-agent: false
          command:
            ["bash", "-c", "pip install -r requirements.txt && pytest -v"]
