agents:
  queue: elasticstack
steps:
  - input: "Buildkite Analytics Configuration"
    fields:
      - text: "Enter your Buildkite Analytics Token"
        key: "analytics_token"
    key: "buildkite-analytics-configuration"

  - label: "🐍 Run Python Tests"
    depends_on: "buildkite-analytics-configuration"
    plugins:
      - docker#v5.12.0:
          image: "python:3.12"
          mount-buildkite-agent: false
          environment: BUILDKITE_ANALYTICS_TOKEN=$(buildkite-agent meta-data get analytics_token)
          commands:
            - pip install --no-cache-dir -r requirements.txt
            - pytest
